# APAGA OS ENDEREÇOS REFERENTE AOS 2 ÚLTIMOS PACIENTES  
DELETE FROM enderecos
WHERE id_endereco IN (79, 80);
# APAGA OS PACIENTES DA TABELA PACIENTES DOS ÚLTIMOS 2 PACIENTES 
DELETE FROM pacientes 
WHERE id_paciente IN (39, 40);
# APAGAR DEFINITIVAMENTE O USUÁRIO APÓS A EXCLUSÃO PRÉVIA DOS DADOS DE RELACIONAMENTO, REMOVENDO AGORA OS DOIS ÚLTIMOS USUÁRIOS DO TIPO PACIENTE
DELETE FROM usuarios
WHERE id_usuario IN (79, 80) AND tipo_usuario = 'Paciente';
# APAGAR OS DOIS ÚLTIMOS CONVÊNIOS 
DELETE FROM convenios 
WHERE id_convenio IN (39,40);
# APAGAR A CONSULTA DO UROLOGISTA COM O EXAME DE ULTRASSONOGRAFIA DA PRÓSTATA
DELETE FROM agendamentos
WHERE id_agendamento = 32;
# APAGAR A RECEITA MÉDICA MAIS ANTIGA DA LISTA
DELETE FROM receitas_medicas
WHERE id_receita = 40;
